[build]
  command = "[ -d _flutter ] || git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter; export PATH=\"$PATH:$(pwd)/_flutter/bin\" && flutter config --enable-web --no-analytics && flutter pub get && flutter build web --release --dart-define=SUPABASE_URL=$SUPABASE_URL --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY"
  publish = "build/web"
